# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'RunApp' do

pod 'Masonry', '~> 0.6.3'
pod 'UICountingLabel', '~> 1.2.0'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'BmobSDK', '~> 1.6.5'
pod 'MJRefresh', '~> 2.4.12'
pod 'SFHFKeychainUtils', '~> 0.0.1'
pod 'FMDB', '~> 2.5'

end

target 'RunAppTests' do

end

target 'RunAppUITests' do

end

